### ISSUE TITLE
Add multiline argument to MatchNext method?

### ISSUE THREAD

**Issue by GCuser99** [sihlfall/vba-regex#3]
I noticed that `Match`, `Test`, `Replace`, and others have a `multiline` input argument but `MatchNext` does not. So in your Example 3, to specify `multiline`, I need to do the following:

```vba
Dim matcherState As MatcherStateTy

matcherState.multiline = True '<-- add this line

Do While StaticRegex.MatchNext(matcherState, regex, exampleString)
   Debug.Print StaticRegex.GetCapture(matcherState, exampleString)
   Debug.Print StaticRegex.GetCaptureByName(matcherState, regex, exampleString, "year")
Loop
```
Is there a reason why `MatchNext` does not have a `multiline` argument?

And taking a step back, why wouldn't `multiline` (and perhaps `localMatch`) be specified once in ` StaticRegex.InitializeRegex` along with `caseInsensitive` argument?

Thanks!

**Comment by sihlfall** [comment]
Dear GCuser99,
Thank you for your suggestions and questions.

1. Why doesn't `MatchNext` have a `multiline` parameter? Firstly, `MatchNext` is intended to be used for successive matches (as in your example). The user should not be required to specify `multiline` (and other flags) each time `MatchNext` is called. Of course, we could add a ternary parameter (`multiline = TRUE` or `FALSE` or unspecified), where unspecified would mean "use the value from `matcherState`", but I think that would be confusing. Second, the idea behind `MatchNext` is to perform successive matches with the same set of flags. Adding flag parameters would encourage changing flags from call to call, which should work, but is not a use case I had in mind. The engine will soon support unbounded modifiers like `(?m)` (the `dev` branch already does), which may mitigate the problem.

2. Why is `multiline` not specified along with `caseInsensitive`? The information about whether the match should be `caseInsensitive` is needed at compile time; a case-insensitive regex has a different bytecode than a case-sensitive one. That's why `caseInsentive` has to be specified from the beginning.

Best regards,
sihlfall
